services:
  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: always
    volumes:
      - ./consul-data:/consul/data
    ports:
      - "8500:8500"
    command: >
      agent -server -ui 
      -node=server-1 
      -bootstrap-expect=1 
      -client=0.0.0.0
      -data-dir=/consul/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  gateway-service:
    image: docker.io/larbipts1/mdescs-services:gateway
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - consul-server
    networks:
      - app-network

  logger-service:
    image: docker.io/larbipts1/mdescs-services:logger
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - rabbitmq
      - consul-server
      - mongo
    networks:
      - app-network

  mastercardcs-service:
    image: docker.io/larbipts1/mdescs-services:mdescs
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - rabbitmq
      - consul-server
    networks:
      - app-network

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
    networks:
      - app-network

  rabbitmq:
    image: 'rabbitmq:3.9-management'
    ports:
      - "5672:5672"       # RabbitMQ AMQP port
      - "15672:15672"     # RabbitMQ Management Plugin web UI port
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  consul-data:
  mongo-data:
